### ISSUE TITLE
jD2Stat run failure due to java.lang.NullPointerException

### ISSUE THREAD

**Issue by cameron-weadick** [chancx/jD2Stat#1]
My attempts at running jD2Stat are failing due to a `java.lang.NullPointerException` error.  

Can you assist with troubleshooting this?  I've pasted my screen output below.    
* No output files are created.   
* Simply calling the help function does not yield an error.  

```
 > java -showversion -Xmx8g -jar jD2Stat_1.0.jar -d D2S -n 1 -k 5 -a aa -i test.fa -o myseq.matrix
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)

     ||||||||||||||||| Parameters |||||||||||||||||

input: test.fa
k selected: 5
n-neighnorhood selected: 1
D2 family selected: D2S
Alphabet selected: acdefghiklmnpqrstvwy
Number of thread: 4
output: myseq.matrix

     ||||||||||||||||| Processing |||||||||||||||||

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
	at Main.readFolder(Main.java:261)
	at Main.readFile(Main.java:232)
	at Main.main(Main.java:1048)
	... 5 more

 > java -showversion -Xmx8g -jar jD2Stat_1.0.jar -h
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)

usage: JIWA
 -a <a>   Alphabet: dna (default) or aa.
 -d <d>   D2 method: D2 (default), D2S, D2St or all (for D2+D2S+D2St).
 -h       print this message.
 -i <i>   input file.
 -k <k>   k-mers length: default=8.
 -n <n>   n-Neighborhood: default=0.
 -o <o>   Output file (distance matrix), default=no output.
 -t <t>   Amount of threads: default=4.
```

**Comment by chancx** [comment]
Thanks. I suspect this is caused by compatibility issue with more recent versions of Java. I have uploaded a version 2 of jD2Stat (also written by Guillaume Bernard, dated April 2019), which addresses this issue. Note that however jD2Stat is no longer maintained and updated, unfortunately due to funding constraint.

**Comment by cameron-weadick** [comment]
Version 2 works — thanks!  

For reference, it required that I use OpenJDK Java and not Oracle Java due to a class recognition issue.  

This is what happened when I used Oracle's version.

```
 > java -showversion -Xmx1g -jar jD2Stat_2.0.jar -d D2n -n 1 -k 5 -a aa -i input.fa -o out.matrix
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

But with OpenJDE's version, all went well:

```
 > /usr/local/Cellar/openjdk/18.0.1.1/bin/java -showversion -Xmx1g -jar jD2Stat_2.0.jar -d D2n -n 1 -k 5 -a aa -i input.fa -o out.matrix
openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment Homebrew (build 18.0.1.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1.1+0, mixed mode, sharing)
     ||||||||||||||||| Parameters |||||||||||||||||

input: input.fa
k selected: 5
n-neighnorhood selected: 1
D2 family selected: D2n
Alphabet selected: acdefghiklmnpqrstvwy
Number of thread: 6
output: out.matrix

     ||||||||||||||||| Processing |||||||||||||||||

--------- k-mers libraries generated in 260.0 ms ---------
------------ Print output done in 49.0 ms  ------------
--------------- D2 matrix done in 343.0 ms ---------------
-------------- Analysis done in 888.0 ms  --------------

     |||||||||||||||| Memory usage ||||||||||||||||

Estimation of Vmem used: init = 536870912(524288K) used = 110075496(107495K) committed = 284164096(277504K) max = 1073741824(1048576K)
```
